project 'IOU.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOU
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/Drive'
  pod 'ReachabilitySwift'

  target 'IOUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
